version: '2'
services:
  jupyter_batchnorm:
    build:
      context: .
      dockerfile: Dockerfile.batchnorm_gpu
    image: "guti1/udacity_dl_batchnorm_gpu"
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    devices:
      - /dev/nvidia0
    user: root
    command: [ "sh", "-c",
               "NB_UID=`ls -nd /home/jovyan/work | cut -d ' ' -f 3` \
                NB_GID=`ls -nd /home/jovyan/work | cut -d ' ' -f 4` \
                start-notebook.sh --NotebookApp.token='' --ip=0.0.0.0 --allow-root"]



